# Generated by Django 3.1.5 on 2021-03-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCovidGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_confirmed', models.JSONField()),
                ('confirmed', models.JSONField()),
                ('death', models.JSONField()),
                ('cured', models.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'current_covid_global',
            },
        ),
        migrations.CreateModel(
            name='CurrentCovidInternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_confirmed', models.JSONField()),
                ('suspected', models.JSONField()),
                ('current_asym', models.JSONField()),
                ('confirmed', models.JSONField()),
                ('death', models.JSONField()),
                ('cured', models.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'current_covid_internal',
            },
        ),
        migrations.CreateModel(
            name='CurrentCovidProvinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('overall_data', models.JSONField()),
                ('city_data', models.JSONField()),
                ('extra_info', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'current_covid_provinces',
            },
        ),
    ]
