# Generated by Django 3.1.5 on 2021-03-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCovidNational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island', models.CharField(max_length=200)),
                ('island_data', models.JSONField()),
                ('island_nation_data', models.JSONField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'current_covid_national',
            },
        ),
    ]
