# Generated by Django 3.1.7 on 2021-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_currentcovidnational'),
    ]

    operations = [
        migrations.CreateModel(
            name='RumorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('authordesc', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('markstyle', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('explain', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('tag', models.JSONField(default=list)),
                ('type', models.IntegerField()),
                ('videourl', models.CharField(default='', max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('coverrect', models.CharField(max_length=200)),
                ('coversqual', models.CharField(max_length=200)),
                ('section', models.CharField(default='', max_length=200)),
                ('iscolled', models.BooleanField(default=False)),
                ('arttype', models.CharField(default='normal', max_length=200)),
            ],
            options={
                'db_table': 'rumor_info',
            },
        ),
    ]
