# Generated by Django 3.1.5 on 2021-04-20 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210420_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 12, 26, 49, 88459)),
        ),
        migrations.AlterField(
            model_name='headlinesnews',
            name='summary',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 12, 26, 49, 95473)),
        ),
    ]
