# Generated by Django 3.1.5 on 2021-04-25 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210425_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPrumors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(default='中国互联网联合辟谣', max_length=200)),
                ('authordesc', models.CharField(default='中国互联网联合辟谣', max_length=200)),
                ('date', models.CharField(db_index=True, max_length=200)),
                ('markstyle', models.CharField(default='fake', max_length=200)),
                ('result', models.CharField(default='假', max_length=200)),
                ('explain', models.CharField(default='谣言', max_length=200)),
                ('abstract', models.TextField(db_index=True, max_length=1000)),
                ('tag', models.JSONField(db_index=True, default=list)),
                ('type', models.IntegerField(default=1)),
                ('videourl', models.CharField(default='', max_length=200)),
                ('cover', models.CharField(default='', max_length=200)),
                ('coverrect', models.CharField(default='', max_length=200)),
                ('coversqual', models.CharField(default='', max_length=200)),
                ('section', models.CharField(default='', max_length=200)),
                ('iscolled', models.BooleanField(default=False)),
                ('arttype', models.CharField(default='normal', max_length=200)),
            ],
            options={
                'db_table': 'nlp_rumors',
            },
        ),
        migrations.AlterField(
            model_name='currentvaccinations',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 16, 12, 49, 7132)),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 16, 12, 49, 10124)),
        ),
    ]
