# Generated by Django 3.1.5 on 2021-03-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_brazildailydata_francedailydata_germanydailydata_globaldailydata_internaldailydata_italydailydata_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentVaccinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('total_vaccinations', models.IntegerField()),
                ('new_vaccinations', models.IntegerField()),
                ('total_vaccinations_per_hundred', models.FloatField()),
            ],
            options={
                'db_table': 'current_vaccinations',
            },
        ),
        migrations.CreateModel(
            name='currentVaccinesNations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('vaccines', models.CharField(max_length=200)),
                ('total_vaccinations', models.CharField(max_length=200)),
                ('total_vaccinations_per_hundred', models.FloatField()),
            ],
            options={
                'db_table': 'current_vaccines_nations',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('top_big_img', models.JSONField(default=list)),
                ('category_id', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('sub_category_name', models.CharField(max_length=200)),
                ('sub_category_cn', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('media_name', models.CharField(max_length=200)),
                ('article_id', models.CharField(max_length=200)),
                ('commond_num', models.CharField(max_length=200)),
                ('publish_time', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField()),
                ('img', models.URLField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='perTrendVaccinesNations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('total_vaccinations_per_hundred', models.FloatField()),
            ],
            options={
                'db_table': 'per_trend_accines_nations',
            },
        ),
        migrations.CreateModel(
            name='totalTrendVaccinesNations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('total_vaccinations', models.FloatField()),
            ],
            options={
                'db_table': 'total_trend_vaccines_nations',
            },
        ),
        migrations.CreateModel(
            name='trendVaccinesInternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('total_vaccinations', models.IntegerField()),
                ('total_vaccinations_per_hundred', models.FloatField()),
            ],
            options={
                'db_table': 'trend_vaccines_internal',
            },
        ),
        migrations.RenameField(
            model_name='currentcovidinternal',
            old_name='suspected',
            new_name='abroad',
        ),
    ]
