# Generated by Django 3.1.5 on 2021-04-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210425_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='currentvaccinations',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 20, 18, 42, 565402)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 20, 18, 42, 568395)),
        ),
    ]
