# Generated by Django 3.1.5 on 2021-04-20 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210420_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questiont',
            new_name='questionid',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 17, 9, 28, 529540)),
        ),
    ]
