# Generated by Django 3.1.5 on 2021-03-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210331_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertrendvaccinesnations',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pertrendvaccinesnations',
            name='total_vaccinations_per_hundred',
        ),
        migrations.RemoveField(
            model_name='pertrendvaccinesnations',
            name='year',
        ),
        migrations.AddField(
            model_name='pertrendvaccinesnations',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
