# Generated by Django 3.1.5 on 2021-04-21 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210420_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvaccinations',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 11, 7, 8, 271569)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 11, 7, 8, 273629)),
        ),
    ]
