# Generated by Django 3.1.5 on 2021-03-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210331_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totaltrendvaccinesnations',
            name='date',
        ),
        migrations.RemoveField(
            model_name='totaltrendvaccinesnations',
            name='total_vaccinations',
        ),
        migrations.RemoveField(
            model_name='totaltrendvaccinesnations',
            name='year',
        ),
        migrations.AddField(
            model_name='totaltrendvaccinesnations',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
