# Generated by Django 3.1.5 on 2021-03-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210331_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_cn',
            field=models.CharField(default='', max_length=200),
        ),
    ]
