# Generated by Django 3.1.5 on 2021-03-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_news_category_cn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='commond_num',
            new_name='comment_num',
        ),
    ]
