# Generated by Django 3.1.5 on 2021-04-01 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210331_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentvaccinations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
