# Generated by Django 3.1.5 on 2021-04-05 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_currentvaccinations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignatedHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=200)),
                ('citys', models.JSONField(default=list)),
                ('cityCnt', models.IntegerField()),
            ],
            options={
                'db_table': 'designated_hospital',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('low_level_count', models.IntegerField()),
                ('medium_level_count', models.IntegerField()),
                ('high_level_count', models.IntegerField()),
                ('city_list', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'risk_level',
            },
        ),
        migrations.CreateModel(
            name='TravelPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('leave_policy_list', models.JSONField(default=list)),
                ('back_policy_list', models.JSONField(default=list)),
                ('stay_info_list', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'travel_policy',
            },
        ),
        migrations.CreateModel(
            name='VaccinationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vaccination_point',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_date', models.DateTimeField(default=datetime.datetime(2021, 4, 5, 16, 6, 42, 334348))),
                ('questiont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
