# Generated by Django 3.1.5 on 2021-04-06 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210405_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlinesNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(default='')),
                ('date', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=400)),
                ('tag_list', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 12, 26, 48, 211766)),
        ),
    ]
