# Generated by Django 3.1.5 on 2021-04-06 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210406_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('progress', models.CharField(max_length=200)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 12, 38, 1, 201206)),
        ),
    ]
