# Generated by Django 3.1.5 on 2021-04-06 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210406_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 21, 42, 58, 320909)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 21, 42, 58, 312907)),
        ),
    ]
