# Generated by Django 3.1.5 on 2021-04-09 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20210406_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 10, 50, 37, 636920)),
        ),
        migrations.AlterField(
            model_name='currentvaccinesnations',
            name='country',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='designatedhospital',
            name='provinceName',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='headlinesnews',
            name='date',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='headlinesnews',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='province',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='abstract',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='date',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='tag',
            field=models.JSONField(db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testagent',
            name='province',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='totaltrendvaccinesnations',
            name='country',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpolicy',
            name='city',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpolicy',
            name='province',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccinationpoint',
            name='province',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 10, 50, 37, 643901)),
        ),
    ]
