# Generated by Django 3.1.5 on 2021-04-09 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20210409_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 14, 14, 22, 553269)),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='cover',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='coverrect',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='coversqual',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='explain',
            field=models.CharField(default='谣言', max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='markstyle',
            field=models.CharField(default='fake', max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='result',
            field=models.CharField(default='假', max_length=200),
        ),
        migrations.AlterField(
            model_name='rumorinfo',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vaccinestatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 14, 14, 22, 564239)),
        ),
    ]
